[project]
name = "simple-mcp"
version = "0.1.0"
description = "A simple mcp server"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.128.0",
    "mcp>=1.25.0",
    "pydantic>=2.12.5",
]
